# Site settings
title: DaveOpsIO
description: DevOps and developer blog by David Charles
url: "https://daveopsio.dev" 
baseurl: "" # leave empty for root domain

# Theme settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 

# Author info
author:
  name: David Charles
  email: daveopsio.cloud@gmail.com

# Optional: Social links
social:
  github: daveopsio
