# Site settings
title: "DaveOpsIO"
description: "DevOps and developer blog by David Charles"
url: "https://daveopsio.dev" 
baseurl: "" # leave empty for root domain

# Theme settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 

github:
another_url: https://daveopsio.dev

#includes
include:
  - _pages

# Author info
author: David Charles
author_email: daveopsio.cloud@gmail.com


# Optional: Social links
social:
  github: daveopsio
